server:
  port: 9902

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/test?authSource=admin&authMechanism=SCRAM-SHA-1

  rabbitmq:
    host: rabbit
    port: 5672
    password: root
    username: root
    virtual-host: /

queue:
  attachment:
    name: AttachmentQueue


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



---

spring:
  profiles: staging
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
