server:
  port: 9902

spring:
  data:
    mongodb:
      username: root
      password: root
      port: 27017
      host: localhost
      database: test

  rabbitmq:
    host: localhost
    port: 5672
    password: root
    username: root
    virtual-host: /

queue:
  attachment:
    name: AttachmentQueue
