server:
  port: 9903

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/cartdb
    username: postgres
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: staging
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root123
    url: jdbc:postgresql://postgres:5432/cartdb
    username: root
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/