server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: staging, prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/