server:
  port: 9901

db:
  username: root
  password: root
  host: localhost
  port: 5432
  name: ecomapp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${db.user}
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.password}
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect

---

spring:
  profiles: staging


db:
  username: root
  password: root123
  host: postgres
  port: 5432
  name: ecomapp

---

spring:
  profiles: prod


db:
  username: root
  password: root123
  host: postgres
  port: 5432
  name: ecomapp
