version: "3"

services:

  auth:
    image: jboss/keycloak
    container_name: keycloak-server
    ports:
      - 8080:8080
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomapp
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9998:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    container_name: rabbit
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080

volumes:
  pgdata:
