version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomapp
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 9999:9999

  auth:
    image: jboss/keycloak
    container_name: keycloak-server
    ports:
      - 8080:8080
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: auth-db
      DB_USER: root
      DB_PASSWORD: root123

  discovery-server:
    image: zios07/discovery-server
    container_name: discovery-server
    restart: always
    ports:
      - 8761:8761
    depends_on:
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: staging

  edge-server:
    image: zios07/edge-server
    container_name: edge-server
    restart: always
    ports:
      - 8765:8765
    depends_on:
      - config-server
      - discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: staging

  config-server:
    image: zios07/config-server
    container_name: config-server
    restart: always
    ports:
      - 8888:8888

  web:
    image: zios07/ecom-web
    container_name: ecom-web
    ports:
      - 80:80

  product-service:
    image: zios07/product-service
    container_name: product-service
    ports:
      - 9901:9901
    restart: always
    depends_on:
      - config-server
      - discovery-server
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: staging

volumes:
  pgdata: