version: "3"

services:
  discovery-server:
    image: zios07/discovery-server
    container_name: discovery-server
    restart: on-failure
    ports:
      - 8761:8761
    depends_on:
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: staging

  edge-server:
    image: zios07/edge-server
    container_name: edge-server
    restart: on-failure
    ports:
      - 8765:8765
    depends_on:
      - config-server
      - discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: staging

  config-server:
    image: zios07/config-server
    container_name: config-server
    restart: always
    ports:
      - 8888:8888
    environment:
      SPRING_PROFILES_ACTIVE: staging
  
  web:
    image: zios07/eco-web:0.0.2
    container_name: eco-web
    restart: on-failure
    ports:
      - 80:80

  product-service:
    image: zios07/product-service:0.0.1
    container_name: product-service
    ports:
      - 9901:9901
    restart: on-failure
    depends_on:
      - config-server
      - discovery-server
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: staging

  attachment-service:
    image: zios07/attachment-service:0.0.1
    container_name: attachment-service
    ports:
      - 9902:9902
    restart: on-failure
    depends_on:
      - config-server
      - discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: staging

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomapp

  mongo:
    image: mongo
    hostname: "mongo"
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 9998:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    container_name: rabbit
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
    

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9999:8080

volumes:
  pgdata:
  mongo:
  rabbit:
