version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: ecomapp

  adminer:
    image: adminer
    ports:
      - 8080:8080

  discovery-server:
    image: zios07/discovery-server
    restart: always
    ports:
      - 8761:8761
    depends_on:
      - config-server
    environment: 
      SPRING_PROFILES_ACTIVE: staging
  
  edge-server:
    image: zios07/edge-server
    restart: always
    ports:
      - 8765:8765
    depends_on:
      - config-server
    environment: 
      SPRING_PROFILES_ACTIVE: staging

  config-server:
    image: zios07/config-server
    restart: always
    ports:
      - 8888:8888

  product-service:
    image: zios07/product-service
    ports:
      - 9901:9901
    depends_on:
      - config-server
      - postgres
    environment: 
      SPRING_PROFILES_ACTIVE: staging
  
  web:
    image: zios07/ecom-web
    ports:
      - 4200:4200
  