apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment-service-deployment
  labels:
    app: attachment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment-service
  template:
    metadata:
      labels:
        app: attachment-service
    spec:
      containers:
      - name: attachment-service
        image: zios07/attachment-service:0.0.1
        ports:
        - containerPort: 9902
        resources:
          limits:
            cpu: ".5"
            memory: "256Mi"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: staging
---

apiVersion: v1
kind: Service
metadata:
  name: attachment-service-service
spec:
  selector:
    app: attachment-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9902
    targetPort: 9902
