apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      hostname: config-server
      containers:
      - name: config-server
        image: zios07/config-server
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: ".5"
            memory: "1Gi"
 
---

apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
