apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      hostname: discovery-server
      containers:
      - name: discovery-server
        image: zios07/discovery-server
        ports:
        - containerPort: 8761
        resources:
          limits:
            cpu: ".1"
            memory: "256Mi"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: staging
 
---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
  - name: "8761"
    port: 8761
    nodePort: 30002
