apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server-deployment
  labels:
    app: edge-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
    spec:
      containers:
      - name: edge-server
        image: zios07/edge-server
        ports:
        - containerPort: 8765
        resources:
          limits:
            cpu: ".1"
            memory: "256Mi"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
 
---

apiVersion: v1
kind: Service
metadata:
  name: edge-server-service
spec:
  selector:
    app: edge-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8765
    targetPort: 8765
