apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      hostname: product-service
      containers:
      - name: product-service
        image: zios07/product-service
        ports:
        - containerPort: 9901
        resources:
          limits:
            cpu: ".2"
            memory: "256Mi"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: staging
 
---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - name: "9901"
    port: 9901
    targetPort: 9901